using UnityEngine;

public class ItmGet : MonoBehaviour
{
    [SerializeField] private GameObject crane;
    [SerializeField] private TargetItem TargetItem;
    [SerializeField] private GameObject audioManager;

 [SerializeField] private GameObject itemGetParticle;
    [SerializeField] private GeneratingManager generatingManager;
    private void Start()
    {
        TargetItem.TargetSet();
        generatingManager.Generation();
    }
    private void OnTriggerEnter2D(Collider2D collision)
    {
        //ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½Ìƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        Instantiate(itemGetParticle,collision.gameObject.transform.position,Quaternion.identity);
        //ï¿½Xï¿½^ï¿½[ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
        if (collision.gameObject.tag == "Star")
        {
            AddScoreOnDestroy(collision, 10);//ï¿½Xï¿½Rï¿½Aï¿½ï¿½10ï¿½_ï¿½ï¿½ï¿½Z
        }
        //ï¿½ï¿½bï¿½pï¿½ï¿½ï¿½[ï¿½Aï¿½bï¿½vï¿½Aï¿½Cï¿½eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½ï¿½Ìï¿½ï¿½ï¿½
        if (collision.gameObject.tag == "BasePowerUp")
        {
            audioManager.GetComponent<GameSceneAudioManager>().PowerUpSound();
            crane.GetComponent<MagneticForceVariable>().AddBase();//ï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÌŠï¿½bï¿½pï¿½ï¿½ï¿½[ï¿½ğ‘‰ï¿½
            AddScoreOnDestroy(collision, 100);
            Debug.Log("ï¿½ï¿½bï¿½lï¿½pï¿½ï¿½ï¿½[ï¿½Aï¿½bï¿½vï¿½I");
        }
        //ï¿½{ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½[ï¿½Aï¿½bï¿½vï¿½ï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½ï¿½Ìï¿½ï¿½ï¿½
        if (collision.gameObject.tag == "RatePowerUp")
        {
            audioManager.GetComponent<GameSceneAudioManager>().PowerUpSound();
            crane.GetComponent<MagneticForceVariable>().AddMagnification();//ï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ì”{ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½[ï¿½ğ‘‰ï¿½
            AddScoreOnDestroy(collision, 100);
            Debug.Log("ï¿½{ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½[ï¿½Aï¿½bï¿½vï¿½I");
        }
        //ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½[ï¿½Aï¿½bï¿½vï¿½ï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½ï¿½Ìï¿½ï¿½ï¿½
        if (collision.gameObject.tag == "WidthPowerUp")
        {
            audioManager.GetComponent<GameSceneAudioManager>().PowerUpSound();
            AddScoreOnDestroy(collision, 100);
            Debug.Log("ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½[ï¿½Aï¿½bï¿½vï¿½I");
        }
        //ï¿½^ï¿½[ï¿½ï¿½ï¿½ñ•œï¿½ï¿½Aï¿½bï¿½vï¿½ï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½ï¿½Ìï¿½ï¿½ï¿½
        if (collision.gameObject.tag == "TurnRecoveryUp")
        {
            audioManager.GetComponent<GameSceneAudioManager>().PowerUpSound();
            AddScoreOnDestroy(collision, 100);
            Debug.Log("ï¿½^ï¿½[ï¿½ï¿½ï¿½ñ•œï¿½ï¿½Aï¿½bï¿½vï¿½I");
        }
        //ï¿½Ú•Wï¿½Aï¿½Cï¿½eï¿½ï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ìï¿½ï¿½ï¿½
        if (collision.gameObject.tag == "Target")
        {
            AddScoreOnDestroy(collision, 1000);
            Debug.Log("ï¿½íœï¿½I");

            if (TargetItem.PushItem[0].name == collision.gameObject.name)
            {
                Debug.Log("ï¿½Ú•Wï¿½ÌƒAï¿½Cï¿½eï¿½ï¿½ï¿½ï¿½ï¿½Qï¿½bï¿½gï¿½I");
                TargetItem.TargetSet();
                generatingManager.Generation();
            }
            else
            {
                Debug.Log("ï¿½^ï¿½[ï¿½Qï¿½bï¿½gï¿½Aï¿½Cï¿½eï¿½ï¿½ï¿½ï¿½ï¿½Qï¿½bï¿½gï¿½I");
            }
        }
    }

    private void AddScoreOnDestroy(Collider2D collision,int addScore)
    {
        Destroy(collision.gameObject);
        ScoreKeep.score += addScore;//ï¿½Xï¿½Rï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½Z
    }
}
